"""create products table

Revision ID: 4d26ef1e0be2
Revises: 693eebe7e00c
Create Date: 2024-06-18 18:07:12.069335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d26ef1e0be2'
down_revision: Union[str, None] = '693eebe7e00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=False),
    sa.Column('secao', sa.String(), nullable=False),
    sa.Column('categoria', sa.Enum('eletronics', 'clothing', 'shoes', 'books', 'games', name='category'), nullable=False),
    sa.Column('estoque_inicial', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
