"""add updated_at colunm to clients table

Revision ID: 693eebe7e00c
Revises: c32e2ae85d1f
Create Date: 2024-06-18 15:09:30.712674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693eebe7e00c'
down_revision: Union[str, None] = 'c32e2ae85d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'updated_at')
    # ### end Alembic commands ###
